# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', tinymce.models.HTMLField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
