# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0004_auto_20170826_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemaster',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='casemaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_module_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casemaster',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='casemaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_module_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='modulemaster',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
