# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20170826_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemaster',
            old_name='added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='modulemaster',
            old_name='added',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='modulemaster',
            old_name='modified',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='casemaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_module_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modulemaster',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
