# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20170826_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casemaster',
            old_name='modified',
            new_name='updated',
        ),
    ]
