# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0008_auto_20170910_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemaster',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='methodologymaster',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modulemaster',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
