# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='modules',
        ),
        migrations.AddField(
            model_name='case',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Module'),
            preserve_default=False,
        ),
    ]
