# Generated by Django 2.0.6 on 2018-07-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sh0t',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
