# Generated by Django 2.0.6 on 2018-08-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180701_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
