# Generated by Django 2.0.8 on 2019-01-29 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_flag_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sh0t',
            name='severity',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
