# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170818_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='note',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='body',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
