# Generated by Django 2.1.7 on 2019-04-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sh0t_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sh0t',
            options={'ordering': ('severity', 'title')},
        ),
    ]
