# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170819_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemaster',
            name='module',
        ),
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'ordering': ('title',)},
        ),
        migrations.DeleteModel(
            name='CaseMaster',
        ),
        migrations.DeleteModel(
            name='ModuleMaster',
        ),
    ]
