# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170819_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bug',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='flag',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='project',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='flag',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
