# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 04:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170819_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Assessment'),
        ),
    ]
