# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_flag_assessment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bug',
            new_name='Shot',
        ),
        migrations.AlterField(
            model_name='flag',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
