# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170820_0825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shot',
            new_name='Sh0t',
        ),
    ]
