# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='note',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='sh0t',
            name='body',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='template',
            name='body',
            field=models.TextField(default=b''),
        ),
    ]
