# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170917_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
        migrations.AlterField(
            model_name='sh0t',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
    ]
