# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 08:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170917_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
